  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/mobilestore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: ostapkmn
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      # Show or not log for each sql query
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate:
        # Hibernate ddl auto (validate, create, create-drop, update)
        ddl-auto: update
        # Naming strategy
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy


  #server:
  #  port: 9000